UCP-3414 Style radio buttons on Marketo forms
SU-UComm/stanford-report pull request #300
Opened 2024-07-11 22:57 UTC by JBCSU

# Summary
- Style radio buttons on Marketo subscribe forms to look (mostly) like checkboxes

# Review By (Date)
- ASAP

# Criticality
- 5 - Only affects the [Subscribe](https://news.stanford.edu/subscribe) page and the new [Campaign Tracking](https://news.stanford.edu/obfuscated-campaign-tracker-1891) page, but we want to launch the Campaign Tracking page soon, and this needs to be in place before we do.

# Review Tasks

## How to test

1. Log in to Matrix so you can see the unpublished pages in the dev environment.
1. Verify my changes worked: Visit [the Campaign Tracker page in the dev environment](https://news.stanford.edu/developreport/campaign-tracker/_nocache), and confirm that the radio buttons look good at all breakpoints, and in both light and dark modes.
1. Verify I didn't introduce any regressions: Visit [the Subscribe page in the dev environment](https://news.stanford.edu/developreport/subscribe-to-stanford-report/_nocache), and confirm that it looks the same as [the live Subscribe page](https://news.stanford.edu/subscribe).

# Associated Issues and/or People
- [UCP-3414](https://stanfordits.atlassian.net/browse/UCP-3414)
- [UCP-3395](https://stanfordits.atlassian.net/browse/UCP-3395)

2024-07-11 23:56 UTC, yvonnetangsu reviewed
Hi @JBCSU This is super close! Your CSS changes (adding the input radio to the checkbox styles) totally makes sense. All is working except border color for the radio buttons, it looks like they're being overridden somewhere else, which prevents the blue border color on hocus from showing up. I haven't dug into the code but here's the inspector screenshot showing the override. 
![Screenshot 2024-07-11 at 4 53 24 PM](https://github.com/user-attachments/assets/a6e44389-590f-4455-9c1b-f6a698a1a343)

2024-07-12 14:48 UTC, iamrentman commented
I see what Yvonne pointed out as well. Appears to only be light mode, dark mode seems fine. In light mode notice the border of the radios stays gray on :hover and :focus but the checkbox border changes to a dark blue on :hover and :focus. These should match.

2024-07-12 14:49 UTC, iamrentman requested changes
I see what Yvonne pointed out as well. Appears to only be light mode, dark mode seems fine. In light mode notice the border of the radios stays gray on :hover and :focus but the checkbox border changes to a dark blue on :hover and :focus. These should match.

2024-07-12 19:08 UTC, JBCSU commented
Thanks for your careful review, @yvonnetangsu and @iamrentman! Those overrides are custom CSS I applied to the form in Marketo to prevent the radio buttons from looking like [this](https://news.stanford.edu/obfuscated-campaign-tracker-1891) until I could get the final styles deployed. I wanted our content team to be able to review the page without being distracted by buttons that span the full width of text area. Oddly, tho, those overrides did not prevent me from seeing the blue border on :hocus.

Anyway, I've removed that custom styling from the form in Marketo. Can you [confirm](https://news.stanford.edu/developreport/campaign-tracker/_nocache) that :hocus behaves properly now?

2024-07-16 15:10 UTC, iamrentman approved these changes
Looks good. Thanks JB!

2024-07-16 17:35 UTC, JBCSU commented
Thanks, @yvonnetangsu & @iamrentman! Merging and deploying now.

2024-07-16 17:37 UTC, merged