DS-775 STANFORD-420 | Single CTA block
SU-UComm/stanford-report pull request #302
Opened 2024-07-16 01:37 UTC by yvonnetangsu

# NOT READY FOR REVIEW
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch or go to the netlify preview
2. Navigate to...
3. Verify...

# Associated Issues and/or People
- JIRA ticket(s) - STANFORD-000
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

2024-08-08 19:23 UTC, yvonnetangsu commented on README.md
> +  FONTAWESOME_PACKAGE_TOKEN=YOUR_FA_PACKAGE_TOKEN npm install
Updated the readme here

2024-08-09 16:29 UTC, iamrentman commented on README.md
> +  FONTAWESOME_PACKAGE_TOKEN=YOUR_FA_PACKAGE_TOKEN npm install
tysm!

2024-08-09 16:35 UTC, iamrentman approved these changes
GTG! 🚀

2024-08-09 16:44 UTC, iamrentman requested changes
When originally approving I hadn't looked at the editorial side of Matrix. I think we can make the CTA fields conditional based on the selection in your `ctaType` field so that all of the different URL fields aren't always displayed but the appropriate one is based on that selection. It'd just make the editorial UI cleaner. We can discuss.

2024-08-09 23:11 UTC, yvonnetangsu commented
> When originally approving I hadn't looked at the editorial side of Matrix. I think we can make the CTA fields conditional based on the selection in your `ctaType` field so that all of the different URL fields aren't always displayed but the appropriate one is based on that selection. It'd just make the editorial UI cleaner. We can discuss.

Hi @iamrentman! This is ready for your review again. I have learned that using https://rjsf-team.github.io/react-jsonschema-form/ doesn't always work. Sometimes it works, and sometimes it doesn't even if I click the "Blank" example first before pasting. However, I have deployed this to the development environment and I believe it is working as intended. Here's my logic:

- If CTA type is "email", display the email address field
- For all other types (link and download), display the internal link, manual link, and new window checkbox fields

I also updated the descriptions in the manifest a bit so it's clearer. Let me know if this works for you.

2024-08-12 14:31 UTC, iamrentman approved these changes
Perf! Thanks for the conditional field update. 🚀

2024-08-12 16:38 UTC, yvonnetangsu commented
Thanks, @iamrentman! I'm going to deploy this to `master`.

2024-08-12 17:05 UTC, merged